# Generated by Django 2.0.9 on 2021-10-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
    ]
