# Generated by Django 2.0.9 on 2021-11-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_remove_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('accno', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='WORKER',
        ),
        migrations.AddField(
            model_name='payment',
            name='accno',
            field=models.CharField(default='', max_length=50),
        ),
    ]
