# Generated by Django 2.0.9 on 2021-11-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20211102_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_request',
            name='seen',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
