# Generated by Django 2.0.9 on 2021-11-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_work_request_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('WORKS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.works')),
            ],
            options={
                'db_table': 'work_image',
            },
        ),
    ]
