# Generated by Django 2.0.9 on 2021-11-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
