# Generated by Django 2.0.9 on 2021-11-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
